include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  strong-mode:
    declaration-casts: true
    implicit-casts: false
    implicit-dynamic: false

errors:
  deprecated_member_use: ignore
  deprecated_member_use_from_same_package: ignore
  unused_local_variable: error
  unused_import: error
  unused_element: error
  invalid_assignment: error
  non_constant_identifier_names: ignore
  prefer_final_fields: error
  avoid_void_async: error
  cancel_subscriptions: error
  public_member_api_docs: error
  always_declare_return_types: error
  always_specify_types: error
  annotate_overrides: error
  avoid_print: error
  avoid_renaming_method_parameters: error
  avoid_types_as_parameter_names: error
  avoid_unused_constructor_parameters: error
  camel_case_types: error
  constant_identifier_names: error
  empty_constructor_bodies: error
  hash_and_equals: error
  iterable_contains_unrelated_type: error
  list_remove_unrelated_type: error
  missing_return: error
  no_duplicate_case_values: error
  prefer_const_constructors: error
  prefer_const_constructors_in_immutables: error
  prefer_const_literals_to_create_immutables: error
  prefer_is_empty: error
  prefer_is_not_empty: error
  recursive_getters: error
  test_types_in_equals: error
  type_annotate_public_apis: error
  unawaited_futures: error
  unnecessary_brace_in_string_interps: error
  unnecessary_getters_setters: error
  unnecessary_null_in_if_null_operators: error
  use_function_type_syntax_for_parameters: error
  use_rethrow_when_possible: error

  exclude:
    - build/**
    - ios/**
    - android/**
    - test/**

code_style_options:
  fix_lints: true
  line_length: 120

  identation:
    spaces: 2

  function_declarations:
    prefer_expression_function_bodies: true
    enable_type_annotations: true
    enforce_parameter_positioning: true

linter:
  rules:
    lines_longer_than_80_chars: false
    annotate_overrides: true
    avoid_as: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_print: true
    flutter_style_todos: true
    no_default_cases: true
    cascade_invocations: false
    unnecessary_this: false
    use_setters_to_change_properties: false
    avoid_catching_errors: false
    prefer_constructors_over_static_methods: false
    always_declare_return_types: true
    library_private_types_in_public_api: false
    avoid_function_literals_in_foreach_calls: false
